package br.com.chamado.model;
// Generated 09/12/2015 11:21:41 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Grupo generated by hbm2java
 */
@ManagedBean(name = "grupo")
@SessionScoped
@Entity
@Table(name = "grupo")
public class Grupo implements java.io.Serializable {

    @Id
    @Column(unique = true, nullable = false)
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private int id;

    @Column(name = "nomegrupo", nullable = false, length = 30)
    private String nomegrupo;
    @OneToMany(fetch = FetchType.LAZY, mappedBy = "grupo")
    private Set grupopaginas = new HashSet(0);

    public Grupo() {
    }

    public int getId() {
	return id;
    }

    public void setId(int id) {
	this.id = id;
    }
    
    public String getNomegrupo() {
	return this.nomegrupo;
    }

    public void setNomegrupo(String nomegrupo) {
	this.nomegrupo = nomegrupo;
    }

    public Set getGrupopaginas() {
	return this.grupopaginas;
    }

    public void setGrupopaginas(Set grupopaginas) {
	this.grupopaginas = grupopaginas;
    }

}
