package br.com.chamado.model;


import java.io.Serializable;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Grupopagina generated by hbm2java
 */
@ManagedBean(name = "grupopagina")
@SessionScoped
@Entity
@Table(name = "grupopagina")
public class GrupoPagina implements Serializable {

    @Id
    @Column(unique = true, nullable = false)
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private int id;
    @Column(nullable = false)
    @ManyToOne
    @JoinColumn(name = "grupo")
    private Grupo grupo;
    @Column(nullable = false)
    @ManyToOne
    @JoinColumn(name = "pagina")
    private Pagina pagina;

    public GrupoPagina() {
    }

    public int getId() {
	return id;
    }

    public void setId(int id) {
	this.id = id;
    }

    public Grupo getGrupo() {
	return this.grupo;
    }

    public void setGrupo(Grupo grupo) {
	this.grupo = grupo;
    }

    public Pagina getPagina() {
	return this.pagina;
    }

    public void setPagina(Pagina pagina) {
	this.pagina = pagina;
    }

    @Override
    public int hashCode() {
	int hash = 5;
	hash = 19 * hash + this.id;
	return hash;
    }

    @Override
    public boolean equals(Object obj) {
	if (obj == null) {
	    return false;
	}
	if (getClass() != obj.getClass()) {
	    return false;
	}
	final GrupoPagina other = (GrupoPagina) obj;
	if (this.id != other.id) {
	    return false;
	}
	return true;
    }
   
}
