package br.com.chamado.model;
// Generated 09/12/2015 11:21:41 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Grupo generated by hbm2java
 */
@ManagedBean(name = "grupo")
@SessionScoped
@Entity
@Table(name = "grupo", schema = "public"
)
public class Grupo implements java.io.Serializable {

    private int codgrupo;
    private String nomegrupo;
    private Set grupopaginas = new HashSet(0);

    public Grupo() {
    }

    public Grupo(int codgrupo, String nomegrupo) {
	this.codgrupo = codgrupo;
	this.nomegrupo = nomegrupo;
    }

    public Grupo(int codgrupo, String nomegrupo, Set grupopaginas) {
	this.codgrupo = codgrupo;
	this.nomegrupo = nomegrupo;
	this.grupopaginas = grupopaginas;
    }

    @Id

    @Column(name = "codgrupo", unique = true, nullable = false)
    public int getCodgrupo() {
	return this.codgrupo;
    }

    public void setCodgrupo(int codgrupo) {
	this.codgrupo = codgrupo;
    }

    @Column(name = "nomegrupo", nullable = false, length = 30)
    public String getNomegrupo() {
	return this.nomegrupo;
    }

    public void setNomegrupo(String nomegrupo) {
	this.nomegrupo = nomegrupo;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "grupo")
    public Set getGrupopaginas() {
	return this.grupopaginas;
    }

    public void setGrupopaginas(Set grupopaginas) {
	this.grupopaginas = grupopaginas;
    }

}