package br.com.chamado.model;
// Generated 09/12/2015 11:21:41 by Hibernate Tools 4.3.1

import java.io.Serializable;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Grupo generated by hbm2java
 */
@ManagedBean(name = "grupo")
@SessionScoped
@Entity
@Table(name = "grupo")
public class Grupo implements Serializable {

    @Id
    @Column(unique = true, nullable = false)
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private int id;
    @Column(name = "nomegrupo", nullable = false, length = 30)
    private String nomegrupo;
    

    public Grupo() {
    }

    public int getId() {
	return id;
    }

    public void setId(int id) {
	this.id = id;
    }
    
    public String getNomegrupo() {
	return this.nomegrupo;
    }

    public void setNomegrupo(String nomegrupo) {
	this.nomegrupo = nomegrupo;
    }

    @Override
    public String toString() {
	return nomegrupo ;
    }

    @Override
    public int hashCode() {
	int hash = 3;
	return hash;
    }
    
    @Override
    public boolean equals(Object obj) {
	if (obj == null) {
	    return false;
	}
	if (getClass() != obj.getClass()) {
	    return false;
	}
	final Grupo other = (Grupo) obj;
	if (this.id != other.id) {
	    return false;
	}
	return true;
    }
    

}
