package br.com.chamado.model;

// Generated 04/12/2015 13:53:59 by Hibernate Tools 4.3.1
import br.com.chamado.model.Usuario;
import java.io.File;
import java.io.IOException;
import java.io.Serializable;
import java.util.Date;
import javax.faces.application.FacesMessage;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;
import javax.faces.context.FacesContext;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.Lob;
import javax.persistence.ManyToOne;

import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.primefaces.model.UploadedFile;


/**
 * Mensagem generated by hbm2java
 */
@ManagedBean(name = "mensagem")
@SessionScoped
@Entity
@Table(name = "mensagem")

public class Mensagem implements Serializable {

    @Id
    @Column(unique = true, nullable = false)
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private int id;
    @Column(name = "numchamado", unique = true, nullable = false)
    private int numeChamado;
    @ManyToOne
    @JoinColumn(name = "codfuncautor", nullable = false)
    private Usuario codfuncautor;
    @Temporal(TemporalType.DATE)
    @Column(name = "data", length = 13)
    private Date data;
    @Column(name = "nomearquivo", length = 10)
    private String nomearquivo;
    @Lob
    @Column(name = "arquivo")
    private byte[] arquivo;
    @Column(name = "texto", nullable = false)
    private String texto;

    public Mensagem() {
    
    }
    
    public int getId() {
	return id;
    }

    public void setId(int id) {
	this.id = id;
    }
    public int getNumeChamado() {
	return numeChamado;
    }

    public void setNumeChamado(int numeChamado) {
	this.numeChamado = numeChamado;
    }

    public Usuario getCodfuncautor() {
        return codfuncautor;
    }

    public void setCodfuncautor(Usuario codfuncautor) {
        this.codfuncautor = codfuncautor;
    }
    
    
     
    public Date getData() {
	return this.data;
    }

    public void setData(Date data) {
	this.data = data;
    }

    public String getNomearquivo() {
	return this.nomearquivo;
    }

    public void setNomearquivo(String nomearquivo) {
	this.nomearquivo = nomearquivo;
    }
   public String getTexto() {
	return this.texto;
    }

    public void setTexto(String texto) {
	this.texto = texto;
    }

    public byte[] getArquivo() {
        return arquivo;
    }

    public void setArquivo(byte[] arquivo) {
        this.arquivo = arquivo;
    }
    
    @Override
    public int hashCode() {
	int hash = 5;
	hash = 17 * hash + this.id;
	return hash;
    }

    @Override
    public boolean equals(Object obj) {
	if (obj == null) {
	    return false;
	}
	if (getClass() != obj.getClass()) {
	    return false;
	}
	final Mensagem other = (Mensagem) obj;
	if (this.id != other.id) {
	    return false;
	}
	return true;
    }
   
}
