package br.com.chamado.model;

// Generated 04/12/2015 13:53:59 by Hibernate Tools 4.3.1
import br.com.chamado.model.Usuario;
import java.util.Date;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Mensagem generated by hbm2java
 */
@ManagedBean(name = "mensagem")
@SessionScoped
@Entity
@Table(name = "mensagem", schema = "public"
)
public class Mensagem implements java.io.Serializable {

    @Id
    @Column(name = "nummensagem", unique = true, nullable = false)
    @GeneratedValue(strategy = GenerationType.AUTO)
    private int nummensagem;
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "numchamado", nullable = false)
    private Chamadoc chamadoc;
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "codfuncautor", nullable = false)
    private Usuario usuario;
    @Temporal(TemporalType.DATE)
    @Column(name = "data", length = 13)
    private Date data;
    @Column(name = "nomearquivo", length = 10)
    private String nomearquivo;
    @Column(name = "arquivo")
    private Long arquivo;
    @Column(name = "texto", nullable = false)
    private String texto;

    public Mensagem() {
    }

    public int getNummensagem() {
	return this.nummensagem;
    }

    public void setNummensagem(int nummensagem) {
	this.nummensagem = nummensagem;
    }

    public Chamadoc getChamadoc() {
	return this.chamadoc;
    }

    public void setChamadoc(Chamadoc chamadoc) {
	this.chamadoc = chamadoc;
    }

    public Usuario getUsuario() {
	return this.usuario;
    }

    public void setUsuario(Usuario usuario) {
	this.usuario = usuario;
    }

    public Date getData() {
	return this.data;
    }

    public void setData(Date data) {
	this.data = data;
    }

    public String getNomearquivo() {
	return this.nomearquivo;
    }

    public void setNomearquivo(String nomearquivo) {
	this.nomearquivo = nomearquivo;
    }

    public Long getArquivo() {
	return this.arquivo;
    }

    public void setArquivo(Long arquivo) {
	this.arquivo = arquivo;
    }

    public String getTexto() {
	return this.texto;
    }

    public void setTexto(String texto) {
	this.texto = texto;
    }

}
