package br.com.chamado.model;
// Generated 09/12/2015 11:21:41 by Hibernate Tools 4.3.1

import java.io.Serializable;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Pagina generated by hbm2java
 */
@ManagedBean(name = "pagina")
@SessionScoped
@Entity
@Table(name = "pagina")
public class Pagina implements Serializable {

    @Id
    @Column(unique = true, nullable = false)
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private int id;
    @Column(nullable = false, length = 30)
    private String descricao;
    @Column(name = "nomepagina", nullable = false, length = 30)
    private String nomepagina;
    
   //@ManyToOne
    //private Permissao permissao;
   
    public Pagina() {
    }

    public int getId() {
	return id;
    }

    public void setId(int id) {
	this.id = id;
    }

    public String getNomepagina() {
	return this.nomepagina;
    }

    public void setNomepagina(String nomepagina) {
	this.nomepagina = nomepagina;
    }

    public String getDescricao() {
        return descricao;
    }

    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }
    /*
    public Permissao getPermissao() {
        return permissao;
    }

    public void setPermissao(Permissao permissao) {
        this.permissao = permissao;
    }*/
   
   
    
    @Override
    public int hashCode() {
	int hash = 7;
	hash = 37 * hash + this.id;
	return hash;
    }

    @Override
    public boolean equals(Object obj) {
	if (obj == null) {
	    return false;
	}
	if (getClass() != obj.getClass()) {
	    return false;
	}
	final Pagina other = (Pagina) obj;
	if (this.id != other.id) {
	    return false;
	}
	return true;
    }

}