package br.com.chamado.model;
// Generated 09/12/2015 11:21:41 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Pagina generated by hbm2java
 */
@Entity
@Table(name = "pagina", schema = "public"
)
public class Pagina implements java.io.Serializable {

    private int codpagina;
    private String nomepagina;
    private Set grupopaginas = new HashSet(0);

    public Pagina() {
    }

    public Pagina(int codpagina, String nomepagina) {
	this.codpagina = codpagina;
	this.nomepagina = nomepagina;
    }

    public Pagina(int codpagina, String nomepagina, Set grupopaginas) {
	this.codpagina = codpagina;
	this.nomepagina = nomepagina;
	this.grupopaginas = grupopaginas;
    }

    @Id

    @Column(name = "codpagina", unique = true, nullable = false)
    public int getCodpagina() {
	return this.codpagina;
    }

    public void setCodpagina(int codpagina) {
	this.codpagina = codpagina;
    }

    @Column(name = "nomepagina", nullable = false, length = 30)
    public String getNomepagina() {
	return this.nomepagina;
    }

    public void setNomepagina(String nomepagina) {
	this.nomepagina = nomepagina;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "pagina")
    public Set getGrupopaginas() {
	return this.grupopaginas;
    }

    public void setGrupopaginas(Set grupopaginas) {
	this.grupopaginas = grupopaginas;
    }

}