package br.com.chamado.model;
// Generated 09/12/2015 11:21:41 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.annotation.Generated;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Pagina generated by hbm2java
 */
@Entity
@Table(name = "pagina", schema = "public"
)
public class Pagina implements java.io.Serializable {

    @Id
    @Column(unique = true, nullable = false)
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private int id;
    @Column(name = "nomepagina", nullable = false, length = 30)
    private String nomepagina;
    @OneToMany(fetch = FetchType.LAZY, mappedBy = "pagina")
    private Set grupopaginas = new HashSet(0);

    public Pagina() {
    }

    public int getId() {
	return id;
    }

    public void setId(int id) {
	this.id = id;
    }

    

    
    public String getNomepagina() {
	return this.nomepagina;
    }

    public void setNomepagina(String nomepagina) {
	this.nomepagina = nomepagina;
    }

    
    public Set getGrupopaginas() {
	return this.grupopaginas;
    }

    public void setGrupopaginas(Set grupopaginas) {
	this.grupopaginas = grupopaginas;
    }

}
