package br.com.chamado.model;
// Generated 04/12/2015 13:53:59 by Hibernate Tools 4.3.1

import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Unidade generated by hbm2java
 */
@ManagedBean(name = "unidade")
@SessionScoped
@Entity
@Table(name = "unidade")
public class Unidade implements java.io.Serializable {

    @Id
    @Column(unique = true, nullable = false)
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private int id;
    @Column(nullable = false, length = 30)
    private String nome;
    @Column(name = "mneumonico", nullable = false, length = 30)
    private String mneumonico;
    @Column(name = "fonePabx", nullable = false, length = 30)
    private String fonePabx;
    @Column(name = "foneDiretor", nullable = false, length = 30)
    private String foneDiretor;
    @Column(name = "endereco", nullable = false, length = 30)
    private String endereco;
    @Column(name = "bairro", nullable = false, length = 30)
    private String bairro;
    @Column(name = "cidade", nullable = false, length = 30)
    private String cidade;

    public Unidade() {
    }

    public String getNome() {
        return nome;
    }

    public void setNome(String nome) {
        this.nome = nome;
    }

    public String getMneumonico() {
        return mneumonico;
    }

    public void setMneumonico(String mneumonico) {
        this.mneumonico = mneumonico;
    }

    public String getFonePabx() {
        return fonePabx;
    }

    public void setFonePabx(String fonePabx) {
        this.fonePabx = fonePabx;
    }

    public String getFoneDiretor() {
        return foneDiretor;
    }

    public void setFoneDiretor(String foneDiretor) {
        this.foneDiretor = foneDiretor;
    }

    public int getId() {
	return id;
    }

    public void setId(int id) {
	this.id = id;
    }
    
    public String getEndereco() {
	return this.endereco;
    }

    public void setEndereco(String endereco) {
	this.endereco = endereco;
    }

    public String getBairro() {
	return this.bairro;
    }

    public void setBairro(String bairro) {
	this.bairro = bairro;
    }

    public String getCidade() {
	return this.cidade;
    }

    public void setCidade(String cidade) {
	this.cidade = cidade;
    }

    @Override
    public String toString() {
	return "Unidade{" + "nome=" + nome + '}';
    }
    
    @Override
    public int hashCode() {
	int hash = 5;
	hash = 29 * hash + this.id;
	return hash;
    }

    @Override
    public boolean equals(Object obj) {
	if (obj == null) {
	    return false;
	}
	if (getClass() != obj.getClass()) {
	    return false;
	}
	final Unidade other = (Unidade) obj;
	if (this.id != other.id) {
	    return false;
	}
	return true;
    }
    
}
