package br.com.chamado.model;
// Generated 04/12/2015 13:53:59 by Hibernate Tools 4.3.1

import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Unidade generated by hbm2java
 */
@ManagedBean(name = "unidade")
@SessionScoped
@Entity
@Table(name = "unidade")
public class Unidade implements java.io.Serializable {

    @Id
    @Column(unique = true, nullable = false)
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private int id;
    @Column(name = "descricao", nullable = false, length = 30)
    private String descricao;
    @Column(name = "razaosocial", nullable = false, length = 30)
    private String razaosocial;
    @Column(name = "endereco", nullable = false, length = 30)
    private String endereco;
    @Column(name = "bairro", nullable = false, length = 30)
    private String bairro;
    @Column(name = "cidade", nullable = false, length = 30)
    private String cidade;

    public Unidade() {
    }

    public int getId() {
	return id;
    }

    public void setId(int id) {
	this.id = id;
    }
    

    public String getDescricao() {
	return this.descricao;
    }

    public void setDescricao(String descricao) {
	this.descricao = descricao;
    }

    public String getRazaosocial() {
	return this.razaosocial;
    }

    public void setRazaosocial(String razaosocial) {
	this.razaosocial = razaosocial;
    }

    public String getEndereco() {
	return this.endereco;
    }

    public void setEndereco(String endereco) {
	this.endereco = endereco;
    }

    public String getBairro() {
	return this.bairro;
    }

    public void setBairro(String bairro) {
	this.bairro = bairro;
    }

    public String getCidade() {
	return this.cidade;
    }

    public void setCidade(String cidade) {
	this.cidade = cidade;
    }

}
