package br.com.chamado.model;
// Generated 04/12/2015 13:53:59 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Unidade generated by hbm2java
 */
@Entity
@Table(name="unidade"
    ,schema="public"
)
public class Unidade  implements java.io.Serializable {


     private int codunidade;
     private String descricao;
     private String razaosocial;
     private String endereco;
     private String bairro;
     private String cidade;
     private Set chamadocs = new HashSet(0);
     private Set usuarios = new HashSet(0);

    public Unidade() {
    }

	
    public Unidade(int codunidade, String descricao, String razaosocial, String endereco, String bairro, String cidade) {
        this.codunidade = codunidade;
        this.descricao = descricao;
        this.razaosocial = razaosocial;
        this.endereco = endereco;
        this.bairro = bairro;
        this.cidade = cidade;
    }
    public Unidade(int codunidade, String descricao, String razaosocial, String endereco, String bairro, String cidade, Set chamadocs, Set usuarios) {
       this.codunidade = codunidade;
       this.descricao = descricao;
       this.razaosocial = razaosocial;
       this.endereco = endereco;
       this.bairro = bairro;
       this.cidade = cidade;
       this.chamadocs = chamadocs;
       this.usuarios = usuarios;
    }
   
     @Id 

    
    @Column(name="codunidade", unique=true, nullable=false)
    public int getCodunidade() {
        return this.codunidade;
    }
    
    public void setCodunidade(int codunidade) {
        this.codunidade = codunidade;
    }

    
    @Column(name="descricao", nullable=false, length=30)
    public String getDescricao() {
        return this.descricao;
    }
    
    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }

    
    @Column(name="razaosocial", nullable=false, length=30)
    public String getRazaosocial() {
        return this.razaosocial;
    }
    
    public void setRazaosocial(String razaosocial) {
        this.razaosocial = razaosocial;
    }

    
    @Column(name="endereco", nullable=false, length=30)
    public String getEndereco() {
        return this.endereco;
    }
    
    public void setEndereco(String endereco) {
        this.endereco = endereco;
    }

    
    @Column(name="bairro", nullable=false, length=30)
    public String getBairro() {
        return this.bairro;
    }
    
    public void setBairro(String bairro) {
        this.bairro = bairro;
    }

    
    @Column(name="cidade", nullable=false, length=30)
    public String getCidade() {
        return this.cidade;
    }
    
    public void setCidade(String cidade) {
        this.cidade = cidade;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="unidade")
    public Set getChamadocs() {
        return this.chamadocs;
    }
    
    public void setChamadocs(Set chamadocs) {
        this.chamadocs = chamadocs;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="unidade")
    public Set getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Set usuarios) {
        this.usuarios = usuarios;
    }




}


