package br.com.chamado.model;
// Generated 04/12/2015 13:53:59 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Usuario generated by hbm2java
 */
@Entity
@Table(name="usuario"
    ,schema="public"
    , uniqueConstraints = @UniqueConstraint(columnNames="usuario") 
)
public class Usuario  implements java.io.Serializable {


     private int codusuario;
     private Unidade unidade;
     private String nome;
     private String usuario;
     private String senha;
     private String email;
     private int tipousuario;
     private Set mensagems = new HashSet(0);

    public Usuario() {
    }

	
    public Usuario(int codusuario, Unidade unidade,String nome, String usuario, String senha, String email, int tipousuario) {
        this.codusuario = codusuario;
        this.unidade = unidade;
        this.usuario = usuario;
        this.nome = nome;
	this.senha = senha;
        this.email = email;
        this.tipousuario = tipousuario;
    }
    public Usuario(int codusuario, Unidade unidade,String nome, String usuario, String senha, String email, int tipousuario, Set mensagems) {
       this.codusuario = codusuario;
       this.unidade = unidade;
       this.nome = nome;
       this.usuario = usuario;
       this.senha = senha;
       this.email = email;
       this.tipousuario = tipousuario;
       this.mensagems = mensagems;
    }
   
     @Id 

    
    @Column(name="codusuario", unique=true, nullable=false)
    public int getCodusuario() {
        return this.codusuario;
    }
    @Column(name="nome", unique=true, nullable=false)
    public String getNome() {
	return nome;
    }

    public void setNome(String nome) {
	this.nome = nome;
    }
    
    public void setCodusuario(int codusuario) {
        this.codusuario = codusuario;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="unidade", nullable=false)
    public Unidade getUnidade() {
        return this.unidade;
    }
    
    public void setUnidade(Unidade unidade) {
        this.unidade = unidade;
    }

    
    @Column(name="usuario", unique=true, nullable=false, length=30)
    public String getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(String usuario) {
        this.usuario = usuario;
    }

    
    @Column(name="senha", nullable=false, length=256)
    public String getSenha() {
        return this.senha;
    }
    
    public void setSenha(String senha) {
        this.senha = senha;
    }

    
    @Column(name="email", nullable=false, length=50)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

    
    @Column(name="tipousuario", nullable=false)
    public int getTipousuario() {
        return this.tipousuario;
    }
    
    public void setTipousuario(int tipousuario) {
        this.tipousuario = tipousuario;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="usuario")
    public Set getMensagems() {
        return this.mensagems;
    }
    
    public void setMensagems(Set mensagems) {
        this.mensagems = mensagems;
    }




}


